cursor #f5e0dc
cursor_text_color #1e1e2e

foreground            #cdd6f4
background            #11111B
selection_foreground  #11111B
selection_background  #f5e0dc
url_color             #89b4fa

# black
color0   #45475a
color8   #585b70

# red
color1   #f38ba8
color9   #eba0ac

# green
color2   #a6e3a1
color10  #94e2d5

# yellow
color3   #f9e2af
color11  #fab387

# blue
color4   #89b4fa
color12  #74c7ec

# magenta
color5   #cba6f7
color13  #f5c2e7

# cyan
color6   #94e2d5
color14  #89dceb

# white
color7   #bac2de
color15  #a6adc8