include colors.conf
# font_family JetBrainsMono Nerd Font
# bold_font JetBrainsMono Nerd Font Bold
# italic_font JetBrainsMono Nerd Font Italic
# bold_italic_font JetBrainsMono Nerd Font Bold Italic

font_size 10.0
window_margin_width 8
modify_font auto

# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
bold_font        family='JetBrainsMono Nerd Font Mono' style=Bold
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTSallow_remote_control yes
