cursor #78a8b7
cursor_text_color #222630

foreground            #78a8b7
background            #222630
selection_foreground  #222630
selection_background  #608491
url_color             #75a9ba

# black
color0   #1b1e26
color8   #6d7076

# red
color1   #e25a80
color9   #e77897

# green
color2   #5ae264
color10  #78e780

# yellow
color3   #7f6ce5
color11  #9686ea

# blue
color4   #75a9ba
color12  #8eb8c6

# magenta
color5   #b7dc6a
color13  #c4e285

# cyan
color6   #75a9ba
color14  #8eb8c6

# white
color7   #88b2c0
color15  #ffffff
