# colors.ini

[colors]
background=171b22
foreground=fdfcfc

regular0=12161b
regular1=ed97bd
regular2=c9da62
regular3=e5a56c
regular4=5d6a88
regular5=806482
regular6=da62d3
regular7=fdfcfc

bright0=66696d
bright1=f0aac9
bright2=d3e17e
bright3=eab586
bright4=7a859d
bright5=978098
bright6=e17edb
bright7=ffffff
