# colors.ini

[colors]
background=1e1e1e
foreground=c4c4c4

regular0=181818
regular1=c2c2c2
regular2=94da62
regular3=737372
regular4=717174
regular5=747174
regular6=717474
regular7=cbcbcb

bright0=6a6a6a
bright1=cdcdcd
bright2=a7e17e
bright3=8c8c8b
bright4=8b8b8d
bright5=8d8b8d
bright6=8b8d8d
bright7=ffffff
