# colors.ini

[colors]
background=0e0e0e
foreground=e0e0e0

regular0=1a1a1a
regular1=ff6b6b
regular2=5fff87
regular3=ffd75f
regular4=5f87ff
regular5=af5fff
regular6=5fd7ff
regular7=d0d0d0

bright0=666666
bright1=ff6b6b
bright2=5fff87
bright3=ffd75f
bright4=5f87ff
bright5=af5fff
bright6=5fd7ff
bright7=ffffff
