cursor #ffffff
cursor_text_color #000000

foreground            #e5e5e5
background            #0e0e0e
selection_foreground  #0e0e0e
selection_background  #b3b3b3
url_color             #7aa2f7

# black
color0   #121212
color8   #666666

# red
color1   #ff5f5f
color9   #ff8787

# green
color2   #5fff87
color10  #87ffaf

# yellow
color3   #ffd75f
color11  #ffe087

# blue
color4   #5f87ff
color12  #87afff

# magenta
color5   #af5fff
color13  #d787ff

# cyan
color6   #5fd7ff
color14  #87e7ff

# white
color7   #d0d0d0
color15  #ffffff