cursor #fdfcfc
cursor_text_color #171b22

foreground            #fdfcfc
background            #171b22
selection_foreground  #171b22
selection_background  #bdbdbf
url_color             #5d6a88

# black
color0   #12161b
color8   #66696d

# red
color1   #ed97bd
color9   #f0aac9

# green
color2   #c9da62
color10  #d3e17e

# yellow
color3   #e5a56c
color11  #eab586

# blue
color4   #5d6a88
color12  #7a859d

# magenta
color5   #806482
color13  #978098

# cyan
color6   #da62d3
color14  #e17edb

# white
color7   #fdfcfc
color15  #ffffff
