# colors.ini

[colors]
background=151521
foreground=e9d1c5

regular0=11111a
regular1=e0b8a4
regular2=6cda62
regular3=c7e56c
regular4=9e9fbb
regular5=cdb6c6
regular6=da6276
regular7=ecd7cc

bright0=65656c
bright1=e6c5b4
bright2=86e17e
bright3=d1ea86
bright4=afb0c7
bright5=d6c3d0
bright6=e17e8f
bright7=ffffff
