cursor #ccc7aa
cursor_text_color #100e1d

foreground            #ccc7aa
background            #100e1d
selection_foreground  #100e1d
selection_background  #979383
url_color             #6a787c

# black
color0   #0d0b17
color8   #61606a

# red
color1   #589ae4
color9   #76ace9

# green
color2   #798580
color10  #919b97

# yellow
color3   #cdc8a9
color11  #d6d2b8

# blue
color4   #6a787c
color12  #859094

# magenta
color5   #746d79
color13  #8d8791

# cyan
color6   #6a787c
color14  #859094

# white
color7   #d2ceb4
color15  #ffffff
