cursor #cec4a6
cursor_text_color #242934

foreground            #cec4a6
background            #242934
selection_foreground  #242934
selection_background  #9e9986
url_color             #5e6c87

# black
color0   #1d212a
color8   #6e7279

# red
color1   #58d4e4
color9   #76dce9

# green
color2   #62da65
color10  #7ee181

# yellow
color3   #747472
color11  #8d8d8b

# blue
color4   #5e6c87
color12  #7b869d

# magenta
color5   #766b7b
color13  #8f8693

# cyan
color6   #da6269
color14  #e17e84

# white
color7   #d4cbb1
color15  #ffffff
