cursor #c4c4c4
cursor_text_color #1e1e1e

foreground            #c4c4c4
background            #1e1e1e
selection_foreground  #1e1e1e
selection_background  #969696
url_color             #717174

# black
color0   #181818
color8   #6a6a6a

# red
color1   #c2c2c2
color9   #cdcdcd

# green
color2   #94da62
color10  #a7e17e

# yellow
color3   #737372
color11  #8c8c8b

# blue
color4   #717174
color12  #8b8b8d

# magenta
color5   #747174
color13  #8d8b8d

# cyan
color6   #717474
color14  #8b8d8d

# white
color7   #cbcbcb
color15  #ffffff
