cursor #e9d1c5
cursor_text_color #151521

foreground            #e9d1c5
background            #151521
selection_foreground  #151521
selection_background  #ae9c97
url_color             #9e9fbb

# black
color0   #11111a
color8   #65656c

# red
color1   #e0b8a4
color9   #e6c5b4

# green
color2   #6cda62
color10  #86e17e

# yellow
color3   #c7e56c
color11  #d1ea86

# blue
color4   #9e9fbb
color12  #afb0c7

# magenta
color5   #cdb6c6
color13  #d6c3d0

# cyan
color6   #da6276
color14  #e17e8f

# white
color7   #ecd7cc
color15  #ffffff
